#NOTE: Autogenerated template by @beauwilliams
# Declaratively set shell recipes a.k.a commands should run in
set shell := ["bash", "-uc"]

# Load environment variables
set dotenv-load := true
# apikey:
#    echo " from .env"

# set positional-arguments := true
# foo:
#   echo justinit
#   echo

# Colours

RED:= "\\033[31m"
GREEN:= "\\033[32m"
YELLOW:= "\\033[33m"
BLUE:= "\\033[34m"
MAGNETA:= "\\033[35m"
CYAN:= "\\033[36m"
WHITE:= "\\033[37m"
BOLD:= "\\033[1m"
UNDERLINE:= "\\033[4m"
INVERTED_COLOURS:= "\\033[7m"
RESET := "\\033[0m"
NEWLINE := "\n"

# Recipes

default:
    @#This recipe will be the default if you run just without an argument, e.g list out available commands
    @just --list --unsorted --list-heading $'{{BOLD}}{{GREEN}}Available recipes:{{NEWLINE}}{{RESET}}'
hello:
    @#Hide the recipe being run in the output using an @ symbol
    @#Here we use our hidden helper to prettify the text
    @just _bold_squares "{{YELLOW}}Hello World!"
display:
    #By default it prints the recipe that was run in output before outputting result
    echo -e "Hello World! {{UNDERLINE}}Here we see the recipe that was run printed also by omitting @ in front of recipe"
whoami $name:
    @#Recipe param as env variable with $ sign
    echo $name
install *PACKAGES:
    @#Recipe param as list of packages
    @ni {{PACKAGES}}
install-dev *PACKAGES:
    @#Recipe param as list of packages
    @ni -D {{PACKAGES}}
build *APP:
    @nx build {{APP}}
build-forge-nx:
    @just build forge-nx-demo-app
FORGE-NX-APP := "forge-nx-demo-app"
forge-register:
    @cd dist/apps/{{FORGE-NX-APP}} && forge register && cd ../..
forge-deploy:
    @cd dist/apps/{{FORGE-NX-APP}} && forge deploy && cd ../..
forge-install:
    @cd dist/apps/{{FORGE-NX-APP}} && forge install && cd ../..

update-workspace:
    @#Update the workspace and deps
    @nx migrate latest
generate-forge-app *APP_NAME:
    @nx g @toolsplus/nx-forge:app {{APP_NAME}}
generate-react-app *APP_NAME:
    @nx g @nrwl/react:app {{APP_NAME}}
dry-generate-forge-app *APP_NAME:
    @nx g @toolsplus/nx-forge:app {{APP_NAME}} --dry-run
dry-generate-react-app *APP_NAME:
    @nx g @nrwl/react:app {{APP_NAME}} --dry-run


# Hidden Recipes

_bold_squares message:
    @#Hidden recipes have _ in front, i.e these can be helpers such as pretty printer below
    @echo -e "{{BOLD}}[{{RESET}}{{message}}{{RESET}}{{BOLD}}]{{RESET}}"
